# Budgie Installation Script for Windows
# Usage: .\install.ps1
# Requires: PowerShell 5.1+

$ErrorActionPreference = "Stop"

$VERSION = "0.1"
$BINARY_NAME = "budgie"
$INSTALL_DIR = "$env:LOCALAPPDATA\budgie"

Write-Host "🐦 Installing Budgie v$VERSION" -ForegroundColor Cyan
Write-Host "================================" -ForegroundColor Cyan
Write-Host ""

# Detect architecture
$UNAME_MACHINE = if ($env:PROCESSOR_ARCHITECTURE -eq "AMD64") {
	"amd64"
} else {
	"arm64"
}

# Select binary based on architecture
if ($UNAME_MACHINE -eq "amd64") {
	$BINARY = "$BINARY_NAME-windows-amd64.exe"
} else {
	$BINARY = "$BINARY_NAME-windows-arm64.exe"
}

if (-not (Test-Path "bin\$BINARY")) {
	Write-Host "❌ Binary not found: bin\$BINARY" -ForegroundColor Red
	Write-Host "   Run: .\build-all.sh first (on Linux/macOS)" -ForegroundColor Yellow
	Write-Host "   or build on Windows with: go build -o bin\$BINARY .\cmd\root\main.go" -ForegroundColor Yellow
	exit 1
}

Write-Host "Platform: Windows" -ForegroundColor Green
Write-Host "Architecture: $UNAME_MACHINE" -ForegroundColor Green
Write-Host "Binary:   $BINARY" -ForegroundColor Green
Write-Host ""

# Create installation directory
Write-Host "📁 Creating directories..." -ForegroundColor Yellow
if (-not (Test-Path $INSTALL_DIR)) {
	New-Item -ItemType Directory -Path $INSTALL_DIR -Force | Out-Null
}
Write-Host "✅ Directories created" -ForegroundColor Green

# Copy binary
Write-Host ""
Write-Host "📦 Installing binary..." -ForegroundColor Yellow
Copy-Item "bin\$BINARY" -Destination "$INSTALL_DIR\$BINARY_NAME.exe" -Force
Write-Host "✅ Binary installed to: $INSTALL_DIR\$BINARY_NAME.exe" -ForegroundColor Green

# Create configuration
Write-Host ""
Write-Host "⚙️  Creating configuration..." -ForegroundColor Yellow

$CONFIG_PATH = "$env:LOCALAPPDATA\budgie\config.yaml"

$configContent = @"
# Budgie Configuration
# Generated by install script

data_dir: "$env:LOCALAPPDATA\budgie\data"
runtime:
  address: "\\.\\pipe\\containerd"

discovery:
  enabled: true
  port: 5353

proxy:
  type: "round-robin"
  health_check_interval: 30s

logging:
  level: "info"
  file: "$env:LOCALAPPDATA\budgie\budgie.log"
"@

Set-Content -Path $CONFIG_PATH -Value $configContent -Encoding UTF8
Write-Host "✅ Configuration created: $CONFIG_PATH" -ForegroundColor Green

# Add to PATH
Write-Host ""
Write-Host "🔧 Adding to PATH..." -ForegroundColor Yellow

$currentPath = [Environment]::GetEnvironmentVariable("Path", "User")
if ($currentPath -notlike "*$INSTALL_DIR*") {
	$newPath = "$currentPath;$INSTALL_DIR"
	[Environment]::SetEnvironmentVariable("Path", $newPath, "User")
	Write-Host "✅ Added to user PATH" -ForegroundColor Green
	Write-Host "⚠️  Please restart your terminal or log out/in for changes to take effect" -ForegroundColor Yellow
} else {
	Write-Host "✅ Already in PATH" -ForegroundColor Green
}

# Create desktop shortcut
$desktopPath = [Environment]::GetFolderPath("Desktop")
$shortcutPath = "$desktopPath\Budgie.lnk"

$WScriptShell = New-Object -ComObject WScript.Shell
$shortcut = $WScriptShell.CreateShortcut($shortcutPath)
$shortcut.TargetPath = "$INSTALL_DIR\$BINARY_NAME.exe"
$shortcut.WorkingDirectory = $INSTALL_DIR
$shortcut.Description = "Budgie - Distributed Container Orchestration Tool"
$shortcut.Save()

Write-Host "✅ Desktop shortcut created" -ForegroundColor Green

Write-Host ""
Write-Host "✅ Installation complete!" -ForegroundColor Green
Write-Host ""
Write-Host "📝 Quick Start:" -ForegroundColor Cyan
Write-Host "   1. Open new terminal (restart needed for PATH)" -ForegroundColor White
Write-Host "   2. Run: budgie nest" -ForegroundColor White
Write-Host "   3. Or:  budgie run example.bun" -ForegroundColor White
Write-Host "   4. Help: budgie --help" -ForegroundColor White
Write-Host ""
Write-Host "📚 Documentation:" -ForegroundColor Cyan
Write-Host "   README.md for full documentation" -ForegroundColor White
Write-Host "   example.bun for container example" -ForegroundColor White
Write-Host ""
