#!/bin/bash
# Installation script for budgie on Linux/macOS
# Usage: sudo ./install.sh [platform]
# platform: optional, auto-detected if not provided

set -e

VERSION="0.1"
BINARY_NAME="budgie"
INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/budgie"
DATA_DIR="/var/lib/budgie"

if [ "$EUID" -ne 0 ]; then
	echo "❌ This script must be run as root (use sudo)"
	exit 1
fi

# Detect platform
if [ -z "$1" ]; then
	UNAME_S=$(uname -s)
	case "$UNAME_S" in
		Linux)
			PLATFORM="linux"
			;;
		Darwin)
			PLATFORM="darwin"
			;;
		*)
			echo "❌ Unsupported platform: $UNAME_S"
			exit 1
			;;
	esac
else
	PLATFORM="$1"
fi

# Select binary based on platform
case "$PLATFORM" in
	linux)
		if [ "$(uname -m)" = "x86_64" ]; then
			BINARY="${BINARY_NAME}-linux-amd64"
		else
			BINARY="${BINARY_NAME}-linux-arm64"
		fi
		;;
	darwin)
		if [ "$(uname -m)" = "x86_64" ]; then
			BINARY="${BINARY_NAME}-darwin-amd64"
		else
			BINARY="${BINARY_NAME}-darwin-arm64"
		fi
		;;
	*)
		echo "❌ Invalid platform: $PLATFORM"
		exit 1
		;;
esac

if [ ! -f "bin/$BINARY" ]; then
	echo "❌ Binary not found: bin/$BINARY"
	echo "   Run: ./build-all.sh first"
	exit 1
fi

echo "🐦 Installing Budgie v${VERSION}"
echo "================================"
echo ""
echo "Platform: $PLATFORM"
echo "Binary:   $BINARY"
echo ""

# Create directories
echo "📁 Creating directories..."
mkdir -p "${CONFIG_DIR}"
mkdir -p "${DATA_DIR}"
mkdir -p "${DATA_DIR}/containers"
echo "✅ Directories created"

# Copy binary
echo ""
echo "📦 Installing binary..."
cp "bin/$BINARY" "${INSTALL_DIR}/${BINARY_NAME}"
chmod +x "${INSTALL_DIR}/${BINARY_NAME}"
echo "✅ Binary installed to: ${INSTALL_DIR}/${BINARY_NAME}"

# Create configuration
echo ""
echo "⚙️  Creating configuration..."
cat > "${CONFIG_DIR}/config.yaml" << 'EOF'
# Budgie Configuration
# Generated by install script

data_dir: "${DATA_DIR}"
runtime:
  address: "/run/containerd/containerd.sock"

discovery:
  enabled: true
  port: 5353

proxy:
  type: "round-robin"  # or "least-connections"
  health_check_interval: 30s

logging:
  level: "info"  # debug, info, warn, error
  file: "/var/log/budgie/budgie.log"
EOF

echo "✅ Configuration created: ${CONFIG_DIR}/config.yaml"

# Set up log directory
mkdir -p /var/log/budgie
touch /var/log/budgie/budgie.log

echo ""
echo "✅ Installation complete!"
echo ""
echo "📝 Quick Start:"
echo "   1. Run: budgie nest"
echo "   2. Or:  budgie run example.bun"
echo "   3. Help: budgie --help"
echo ""
echo "📚 Documentation:"
echo "   README.md for full documentation"
echo "   example.bun for container example"
echo ""
